export const CHUC_VU = [
	{ id: 0, label: 'Cán bộ' },
	{ id: 1, label: 'Đội phó' },
	{ id: 2, label: 'Tổng hợp đội' },
	{ id: 3, label: 'Đội trưởng' },
	{ id: 4, label: 'Giúp việc PTT' },
	{ id: 5, label: 'Phó trưởng Công an Quận' },
	{ id: 6, label: 'Trưởng Công an Quận' },
	{ id: 9, label: 'Quản trị viên' },
];

export const TEN_CHUC_DANH = [
	'Cán bộ',
	'Cán bộ điều tra',
	'Điều tra viên',
	'Phó Thủ trưởng Cơ quan điều tra',
	'Thủ trưởng Cơ quan điều tra',
];

export enum MA_CHUC_VU {
	CAN_BO,
	DOI_PHO,
	TONG_HOP_DOI,
	DOI_TRUONG,
	GIUP_VIEC_PTT,
	LANH_DAO,
	QUAN_TRI_VIEN = 9,
}

export const TU_CACH_TO_TUNG = [
	{ id: 1, label: 'Người bị tố giác' },
	{ id: 2, label: 'Người bị kiến nghị khởi tố' },
	{ id: 3, label: 'Người bị giữ trong trường hợp khẩn cấp' },
	{ id: 4, label: 'Người bị bắt' },
	{ id: 5, label: 'Người bị tạm giữ' },
	{ id: 13, label: 'Người vi phạm hành chính' },
	{ id: 6, label: 'Bị can' },
	{ id: 7, label: 'Người tố giác, báo tin về tội phạm, kiến nghị khởi tố' },
	{ id: 8, label: 'Bị hại' },
	{ id: 9, label: 'Người có quyền lợi, nghĩa vụ liên quan đến vụ án' },
	{ id: 10, label: 'Người làm chứng' },
	{ id: 11, label: 'Người chứng kiến' },
	{ id: 12, label: 'Người liên quan khác' },
];

// export const TU_CACH_TO_TUNG_KHOI_TO = [
// 	{ id: 1, label: 'Người bị hại' },
// 	{ id: 2, label: 'Bị can' },
// 	{ id: 3, label: 'Người làm chứng' },
// 	{ id: 4, label: 'Người liên quan khác' },
// ];

export const TRUONG_HOP_BAT = [
	'Đầu thú',
	'Tự thú',
	'Bắt người phạm tội quả tang',
	'Bắt người đang bị truy nã',
	'Bắt bị can, bị cáo để tạm giam',
	'Bắt người bị giữ trong trường hợp khẩn cấp',
];

export enum PHAN_LOAI_TIN {
	TO_GIAC_TOI_PHAM = 'Tố giác về tội phạm',
	TIN_BAO_TOI_PHAM = 'Tin báo về tội phạm',
	KIEN_NGHI_KHOI_TO = 'Kiến nghị khởi tố',
	CQDT_PHAT_HIEN = 'CQĐT trực tiếp phát hiện',
}

export enum LOAI_TOI_PHAM {
	IT_NGHIEM_TRONG = 'Ít nghiêm trọng',
	NGHIEM_TRONG = 'Nghiêm trọng',
	RAT_NGHIEM_TRONG = 'Rất nghiêm trọng',
	DAC_BIET_NGHIEM_TRONG = 'Đặc biệt nghiêm trọng',
}

export const KET_QUA_DON = ['Tạm đình chỉ', 'Không khởi tố', 'Khởi tố'];

export const KET_QUA_AN = [
	'Tạm đình chỉ',
	'Gia hạn',
	'Kết luận điều tra',
	'Kết luận điều tra (Bổ sung)',
	'Kết luận điều tra (Lại)',
	'Kết luận điều tra (Đình chỉ)',
];

export const PHUONG_THUC_PHAM_TOI = [
	'Trộm quả tang',
	'Trộm đột nhập',
	'Trộm cơ hội',
	'Trộm chung cư',
	'Trộm mới',
	'Trộm truyền thống',
	'Lừa đảo truyền thống',
	'Lừa đảo qua công nghệ cao',
	'Lừa đảo qua mạng xã hội Facebook',
	'Lừa đảo qua mạng xã hội Zalo',
	'Lừa đảo qua mạng xã hội Viber',
	'Lừa đảo qua mạng xã hội Telegram',
	'Lừa đảo qua mạng xã hội khác',
	'Lừa đảo giả danh người thân',
	'Lừa đảo bằng giả danh cán bộ tư pháp',
	'Lừa đảo mới',
	'Chiếm đoạt tài sản (Điều 290) dưới hình thức nhận làm cộng tác viên sàn thương mại điện tử',
	'Chiếm đoạt tài sản (Điều 290) bằng gửi liên kết lạ (Link)',
	'Chiếm đoạt tài sản (Điều 290) mới',
	'Cướp giật tài sản bằng phương tiện giao thông',
	'Cướp giật tài sản chạy bộ',
	'Cướp giật tài sản phương thức mới',
	'Cướp tài sản do đòi nợ',
	'Cướp tài sản truyền thống',
	'Cướp tài sản mới',
	'Giết người dùng vũ khí nóng',
	'Giết người dùng vũ khí thô sơ',
	'Giết người bằng tay không',
	'Giết người bằng đầu độc',
	'Giết người bằng hình thức mới',
	'Cố ý gây thương tích bằng vũ khí nóng',
	'Cố ý gây thương tích bằng vũ khí thô sơ',
	'Cố ý gây thương tích bằng hung khí',
	'Cố ý gây thương tích bằng tay không',
	'Cố ý gây thương tích bằng phương tiện giao thông',
	'Cố ý gây thương tích bằng hình thức mới',
	'Đánh bạc bằng trang Web',
	'Đánh bạc bằng ứng dụng',
	'Đánh bạc truyền thống',
	'Đánh bạc dạng cá độ',
	'Đánh bạc dạng sát phạt',
	'Đánh bạc hình thức mới',
	'Tổ chức đánh bạc bằng trang Web',
	'Tổ chức đánh bạc bằng ứng dụng',
	'Tổ chức đánh bạc truyền thống',
	'Tổ chức Đánh bạc dạng cá độ',
	'Tổ chức Đánh bạc dạng sát phạt',
	'Tổ chức Đánh bạc hình thức mới',
	'Phạm tội có sử dụng vũ khí nóng',
	'Phạm tội có sử dụng vũ khí thô sơ',
	'Phạm tội có sử dụng hung khí',
	'Phạm tội bằng hình thức truyền thống',
	'Phạm tội bằng hình thức phi truyền thống',
];

export const NOI_THUC_HIEN_PHAM_TOI = [
	'Nhà riêng',
	'Chung cư',
	'Công cộng',
	'Không gian mạng',
	'Cơ sở vàng bạc',
	'Ngân hàng',
];

export const TEN_MUC_DO_UU_TIEN = [
	{ id: 0, label: 'Thấp', color: '#87d068' },
	{ id: 1, label: 'Thường', color: '#108ee9' },
	{ id: 2, label: 'Cao', color: '#fb3' },
	{ id: 3, label: 'Khẩn', color: '#f50' },
];

export const TEN_TRANG_THAI_CONG_VIEC = [
	{ id: 0, label: 'Mới tạo', color: 'gold' },
	{ id: 1, label: 'Mới giao', color: 'magenta' },
	{ id: 2, label: 'Đã tiếp nhận', color: 'purple' },
	{ id: 3, label: 'Đang thực hiện', color: 'geekblue' },
	{ id: 4, label: 'Đã thực hiện', color: 'blue' },
	{ id: 5, label: 'Chưa đạt', color: 'red' },
	{ id: 6, label: 'Xác nhận', color: 'cyan' },
	{ id: 7, label: 'Hoàn thành', color: 'green' },
	{ id: 8, label: 'Hủy', color: 'default' },
];

export enum MA_TRANG_THAI_CONG_VIEC {
	MOI_TAO,
	MOI_GIAO,
	DA_TIEP_NHAN,
	DANG_THUC_HIEN,
	DA_THUC_HIEN,
	CHUA_DAT,
	XAC_NHAN,
	HOAN_THANH,
	HUY,
}

export const TEN_VAN_BAN_TO_TUNG = [
	'Thông báo về việc tiếp nhận nguồn tin về tội phạm',
	'Phiếu chuyển nguồn tin về tội phạm',
	'Thông báo về việc Thủ trưởng Cơ quan điều tra trực tiếp thụ lý giải quyết nguồn tin về tội phạm',
	'Quyết định phân công Phó Thủ trưởng Cơ quan điều tra giải quyết nguồn tin về tội phạm',
	'Quyết định phân công Điều tra viên, Cán bộ điều tra giải quyết nguồn tin về tội phạm',
	'Quyết định thay đổi Phó Thủ trưởng Cơ quan điều tra giải quyết nguồn tin về tội phạm',
	'Quyết định thay đổi Điều tra viên, Cán bộ điều tra giải quyết nguồn tin về tội phạm',
	'Quyết định ủy thác giải quyết nguồn tin về tội phạm',
	'Quyết định phân công Phó Thủ trưởng Cơ quan điều tra thực hiện Quyết định ủy thác giải quyết nguồn tin về tội phạm',
	'Quyết định phân công Điều tra viên, Cán bộ điều tra thực hiện Quyết định ủy thác giải quyết nguồn tin về tội phạm',
	'Quyết định về việc tham gia tố tụng',
	'Đề nghị gia hạn thời hạn giải quyết nguồn tin về tội phạm',
	'Báo cáo kết thúc giải quyết nguồn tin về tội phạm',
	'Quyết định tách nguồn tin về tội phạm',
	'Quyết định tạm đình chỉ việc giải quyết nguồn tin về tội phạm',
	'Quyết định phục hồi việc giải quyết nguồn tin về tội phạm',
	'Quyết định không khởi tố vụ án hình sự',
	'Thông báo kết quả giải quyết nguồn tin về tội phạm ',
	'Thông báo về việc người phạm tội ',
	'Quyết định khởi tố vụ án hình sự',
	'Quyết định thay đổi Quyết định khởi tố vụ án hình sự',
	'Quyết định bổ sung Quyết định khởi tố vụ án hình sự',
	'Quyết định huỷ bỏ Quyết định khởi tố vụ án hình sự',
	'Thông báo về việc không khởi tố vụ án hình sự',
	'Thông báo về việc huỷ bỏ quyết định khởi tố vụ án hình sự',
	'Thông báo về việc phục hồi điều tra vụ án hình sự',
	'Quyết định nhập vụ án hình sự',
	'Quyết định tách vụ án hình sự',
	'Quyết định tách hành vi và tài liệu liên quan trong vụ án hình sự',
	'Quyết định ủy quyền khi Thủ trưởng Cơ quan điều tra vắng mặt',
	'Quyết định phân công Phó Thủ trưởng Cơ quan điều tra tiến hành khởi tố, điều tra vụ án hình sự',
	'Quyết định phân công bổ sung Phó Thủ trưởng Cơ quan điều tra tiến hành điều tra vụ án hình sự',
	'Quyết định thay đổi Phó Thủ trưởng Cơ quan điều tra tiến hành điều tra vụ án hình sự',
	'Quyết định hủy bỏ Quyết định phân công Phó Thủ trưởng Cơ quan điều tra tiến hành khởi tố, điều tra vụ án hình sự',
	'Quyết định phân công Điều tra viên, Cán bộ điều tra  tiến hành điều tra vụ án hình sự',
	'Quyết định phân công bổ sung Điều tra viên, Cán bộ điều tra tiến hành điều tra vụ án hình sự',
	'Quyết định thay đổi Điều tra viên, Cán bộ điều tra tiến hành điều tra vụ án hình sự',
	'Quyết định thay đổi quyết định/lệnh của Phó Thủ trưởng Cơ quan điều tra/Điều tra viên',
	'Quyết định huỷ bỏ quyết định/lệnh của Phó Thủ trưởng Cơ quan điều tra/Điều tra viên',
	'Quyết định khởi tố bị can',
	'Quyết định bổ sung Quyết định khởi tố bị can',
	'Quyết định thay đổi Quyết định khởi tố bị can',
	'Đề nghị phê chuẩn Quyết định khởi tố bị can',
	'Đề nghị phê chuẩn Quyết định bổ sung Quyết định khởi tố bị can',
	'Đề nghị phê chuẩn Quyết định thay đổi Quyết định khởi tố bị can',
	'Kiến nghị tạm đình chỉ chức vụ của bị can ',
	'Quyết định ủy thác điều tra',
	'Quyết định phân công Phó Thủ trưởng Cơ quan điều tra tiến hành giải quyết ủy thác điều tra',
	'Quyết định phân công Điều tra viên, Cán bộ điều tra tiến hành giải quyết ủy thác điều tra',
	'Quyết định rút vụ án để điều tra',
	'Đề nghị ra Quyết định chuyển vụ án hình sự ',
	'Đề nghị gia hạn thời hạn điều tra vụ án hình sự',
	'Lệnh giữ người trong trường hợp khẩn cấp',
	'Lệnh bắt người bị giữ trong trường hợp khẩn cấp',
	'Đề nghị phê chuẩn Lệnh bắt người bị giữ trong trường hợp khẩn cấp',
	'Thông báo về việc giữ người trong trường hợp khẩn cấp; ',
	'Thông báo về việc bắt người bị giữ trong trường hợp khẩn cấp; ',
	'Thông báo về việc bắt người phạm tội quả tang; ',
	'Thông báo về việc bắt người đang bị truy nã',
	'Lệnh bắt bị can để tạm giam',
	'Đề nghị phê chuẩn Lệnh bắt bị can để tạm giam',
	'Quyết định tạm giữ',
	'Quyết định gia hạn tạm giữ',
	'Đề nghị phê chuẩn Quyết định gia hạn tạm giữ',
	'Lệnh tạm giam',
	'Đề nghị phê chuẩn Lệnh tạm giam',
	'Thông báo về việc áp dụng biện pháp tạm giam',
	'Đề nghị gia hạn tạm giam',
	'Quyết định về việc bảo lĩnh',
	'Đề nghị phê chuẩn Quyết định về việc bảo lĩnh',
	'Lệnh cấm đi khỏi nơi cư trú',
	'Thông báo về việc áp dụng biện pháp cấm đi khỏi nơi cư trú',
	'Quyết định tạm hoãn xuất cảnh',
	'Thông báo về việc áp dụng biện pháp tạm hoãn xuất cảnh',
	'Quyết định thay thế biện pháp ngăn chặn',
	'Đề nghị thay thế biện pháp ngăn chặn',
	'Quyết định hủy bỏ biện pháp ngăn chặn',
	'Đề nghị hủy bỏ biện pháp ngăn chặn',
	'Quyết định trả tự do',
	'Quyết định truy nã ',
	'Quyết định truy nã ',
	'Quyết định đình nã',
	'Quyết định giao người thân thích của người bị tạm giữ cho người thân thích khác hoặc chính quyền xã, phường, thị trấn chăm nom',
	'Quyết định giao người thân thích của người bị tạm giam cho người thân thích khác hoặc chính quyền xã, phường, thị trấn chăm nom',
	'Thông báo về việc giao người thân thích của người bị tạm giữ, tạm giam cho người thân thích khác hoặc chính quyền xã, phường, thị trấn chăm nom',
	'Quyết định áp dụng biện pháp bảo quản tài sản của người bị tạm giữ',
	'Quyết định áp dụng biện pháp bảo quản tài sản của người bị tạm giam',
	'Thông báo về việc áp dụng biện pháp bảo quản tài sản của người bị tạm giữ, tạm giam',
	'Quyết định áp giải',
	'Quyết định dẫn giải',
	'Lệnh kê biên tài sản',
	'Quyết định hủy bỏ Lệnh kê biên tài sản',
	'Lệnh phong tỏa tài khoản',
	'Quyết định hủy bỏ Lệnh phong tỏa tài khoản',
	'Thông báo về việc hủy bỏ biện pháp kê biên tài sản, phong tỏa tài khoản',
	'Đề nghị áp dụng biện pháp bắt buộc chữa bệnh',
	'Lệnh khám xét khẩn cấp',
	'Thông báo về việc khám xét khẩn cấp',
	'Lệnh khám xét',
	'Đề nghị phê chuẩn Lệnh khám xét',
	'Lệnh thu giữ khẩn cấp thư tín, điện tín, bưu kiện, bưu phẩm',
	'Thông báo về việc thu giữ khẩn cấp thư tín, điện tín, bưu kiện, bưu phẩm',
	'Lệnh thu giữ thư tín, điện tín, bưu kiện, bưu phẩm',
	'Đề nghị phê chuẩn Lệnh thu giữ thư tín, điện tín, bưu kiện, bưu phẩm',
	'Phiếu yêu cầu trích xuất',
	'Quyết định tạm giữ tài sản, đồ vật, tài liệu',
	'Quyết định xử lý tài sản, đồ vật, tài liệu',
	'Yêu cầu cơ quan, tổ chức, cá nhân cung cấp chứng cứ, đồ vật, tài liệu, dữ liệu điện tử',
	'Quyết định xử lý vật chứng',
	'Lệnh nhập kho vật chứng',
	'Lệnh xuất kho vật chứng',
	'Yêu cầu tra cứu dấu vết vân tay hiện trường',
	'Quyết định khai quật và khám nghiệm tử thi',
	'Quyết định thực nghiệm điều tra',
	'Quyết định trưng cầu giám định',
	'Quyết định trưng cầu giám định bổ sung',
	'Quyết định trưng cầu giám định lại',
	'Thông báo về việc không chấp nhận đề nghị trưng cầu giám định',
	'Thông báo về việc không chấp nhận đề nghị trưng cầu giám định bổ sung/giám định lại',
	'Thông báo kết luận giám định',
	'Yêu cầu định giá tài sản',
	'Yêu cầu định giá lại tài sản',
	'Thông báo về nội dung kết luận định giá tài sản',
	'Thông báo không chấp nhận đề nghị định giá lại tài sản',
	'Quyết định trưng cầu người phiên dịch',
	'Quyết định trưng cầu người dịch thuật',
	'Quyết định thay đổi trưng cầu người phiên dịch hoặc người dịch thuật',
	'Lệnh trích xuất và áp giải (theo quy định tại Điều 20 Luật thi hành tạm giữ, tạm giam)',
	'Thông báo về việc tiến hành các biện pháp điều tra',
	'Yêu cầu tra cứu ',
	'Yêu cầu thống kê tiền án, tiền sự',
	'Quyết định tạm đình chỉ điều tra vụ án hình sự ',
	'Thông báo về việc tạm đình chỉ điều tra vụ án hình sự',
	'Quyết định đình chỉ điều tra vụ án hình sự ',
	'Quyết định phục hồi điều tra vụ án hình sự ',
	'Quyết định tạm đình chỉ điều tra bị can',
	'Quyết định đình chỉ điều tra bị can',
	'Quyết định phục hồi điều tra bị can',
	'Quyết định tạm đình chỉ điều tra vụ án hình sự đối với bị can',
	'Quyết định đình chỉ điều tra vụ án hình sự đối với bị can',
	'Quyết định phục hồi điều tra vụ án hình sự đối với bị can',
	'Bản kết luận điều tra vụ án hình sự đề nghị truy tố',
	'Bản kết luận điều tra vụ án hình sự trong trường hợp đình chỉ điều tra',
	'Bản kết luận điều tra bổ sung vụ án hình sự',
	'Thông báo về việc kết thúc điều tra vụ án hình sự',
	'Yêu cầu phân công người bào chữa (Trong trường hợp chỉ định người bào chữa)',
	'Thông báo về việc đăng ký bào chữa',
	'Thông báo về việc đăng ký bảo vệ quyền và lợi ích hợp pháp',
	'Thông báo từ chối việc đăng ký bào chữa',
	'Thông báo về việc hủy bỏ đăng ký bào chữa',
	'Thông báo về việc thay đổi/hủy bỏ đăng ký bảo vệ quyền và lợi ích hợp pháp của bị hại, đương sự…',
	'Thông báo cho người bào chữa về việc tiến hành hoạt động điều tra',
	'Quyết định áp dụng biện pháp khiển trách',
	'Quyết định áp dụng biện pháp hòa giải tại cộng đồng',
	'Quyết định áp dụng biện pháp giáo dục tại xã, phường, thị trấn',
	'Quyết định giao người bị buộc tội là người dưới 18 tuổi cho người đại diện giám sát',
	'Quyết định thay đổi người đại diện giám sát người bị buộc tội là người dưới 18 tuổi',
	'Quyết định áp dụng thủ tục rút gọn',
	'Quyết định hủy bỏ Quyết định áp dụng thủ tục rút gọn',
	'Quyết định đề nghị truy tố theo thủ tục rút gọn',
	'Đề nghị áp dụng biện pháp bảo vệ',
	'Đề nghị thay đổi biện pháp bảo vệ',
	'Đề nghị bổ sung biện pháp bảo vệ',
	'Quyết định áp dụng biện pháp bảo vệ',
	'Thông báo về việc không cần thiết áp dụng biện pháp bảo vệ',
	'Quyết định thay đổi biện pháp bảo vệ',
	'Quyết định chấm dứt áp dụng biện pháp bảo vệ',
	'Quyết định thay đổi/bổ sung biện pháp bảo vệ',
	'Quyết định khởi tố bị can đối với pháp nhân',
	'Đề nghị phê chuẩn Quyết định khởi tố bị can đối với pháp nhân',
	'Quyết định thay đổi Quyết định khởi tố bị can đối với pháp nhân',
	'Quyết định bổ sung Quyết định khởi tố bị can đối với pháp nhân',
	'Đề nghị phê chuẩn Quyết định thay đổi Quyết định khởi tố bị can đối với pháp nhân',
	'Đề nghị phê chuẩn Quyết định bổ sung Quyết định khởi tố bị can đối với pháp nhân ',
	'Quyết định tạm đình chỉ điều tra bị can đối với pháp nhân',
	'Quyết định đình chỉ điều tra bị can đối với pháp nhân',
	'Quyết định phục hồi điều tra bị can đối với pháp nhân',
	'Đề nghị pháp nhân cử người đại diện theo pháp luật tham gia tố tụng',
	'Quyết định chỉ định người đại diện theo pháp luật của pháp nhân tham gia tố tụng',
	'Quyết định kê biên tài sản của pháp nhân',
	'Biên bản kê biên tài sản của pháp nhân',
	'Quyết định phong tỏa tài khoản của pháp nhân',
	'Biên bản phong tỏa tài khoản của pháp nhân',
	'Quyết định hủy bỏ biện pháp kê biên tài sản, phong tỏa tài khoản của pháp nhân',
	'Quyết định thay đổi biện pháp cưỡng chế đối với pháp nhân',
	'Quyết định tạm đình chỉ có thời hạn hoạt động của pháp nhân',
	'Đề nghị phê chuẩn Quyết định tạm đình chỉ có thời hạn hoạt động của pháp nhân',
	'Quyết định buộc pháp nhân phải nộp một khoản tiền để bảo đảm thi hành án',
	'Đề nghị phê chuẩn Quyết định buộc pháp nhân phải nộp một khoản tiền để đảm bảo thi hành án',
	'Bản kết luận điều tra vụ án hình sự đối với pháp nhân đề nghị truy tố',
	'Bản kết luận điều tra vụ án hình sự đối với pháp nhân trong trường hợp đình chỉ điều tra',
	'Công văn đôn đốc',
	'Công văn',
];
