export const CHANGE_PAGE_TITLE = 'CHANGE_PAGE_TITLE';
export const CHANGE_MENU_ACTIVE = 'CHANGE_MENU_ACTIVE';

export const LOGOUT = 'LOGOUT';
export const SET_AUTH = 'SET_AUTH';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_COLLAPSE_SIDEBAR = 'TOGGLE_COLLAPSE_SIDEBAR';
