TRUNCATE `toi_danhs`;
INSERT INTO `toi_danhs` (`ma_toi_danh`, `toi_danh`) VALUES
('108', 'Tội phản bội Tổ quốc'),
('109', 'Tội hoạt động nhằm lật đổ chính quyền nhân dân'),
('110', 'Tội gián điệp'),
('111', 'Tội xâm phạm an ninh lãnh thổ'),
('112', 'Tội bạo loạn'),
('113', 'Tội khủng bố nhằm chống chính quyền nhân dân'),
('115', 'Tội phá hoại việc thực hiện các chính sách kinh tế - xã hội'),
('116', 'Tội phá hoại chính sách đoàn kết'),
('117', 'Tội làm, tàng trữ, phát tán hoặc tuyên truyền thông tin, tài liệu, vật phẩm nhằm chống Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam'),
('118', 'Tội phá rối an ninh'),
('119', 'Tội chống phá cơ sở giam giữ'),
('120', 'Tội tổ chức, cưỡng ép, xúi giục người khác trốn đi nước ngoài hoặc trốn ở lại nước ngoài nhằm chống chính quyền nhân dân'),
('121', 'Tội trốn đi nước ngoài hoặc trốn ở lại nước ngoài nhằm chống chính quyền nhân dân'),
('123', 'Tội giết người'),
('124', 'Tội giết hoặc vứt bỏ con mới đẻ'),
('125', 'Tội giết người trong trạng thái tinh thần bị kích động mạnh'),
('126', 'Tội giết người do vượt quá giới hạn phòng vệ chính đáng hoặc do vượt quá mức cần thiết khi bắt giữ người phạm tội'),
('127', 'Tội làm chết người trong khi thi hành công vụ'),
('128', 'Tội vô ý làm chết người'),
('129', 'Tội vô ý làm chết người do vi phạm quy tắc nghề nghiệp hoặc quy tắc hành chính'),
('130', 'Tội bức tử'),
('131', 'Tội xúi giục hoặc giúp người khác tự sát'),
('132', 'Tội không cứu giúp người đang ở trong tình trạng nguy hiểm đến tính mạng'),
('133', 'Tội đe dọa giết người'),
('134', 'Tội cố ý gây thương tích hoặc gây tổn hại cho sức khoẻ của người khác'),
('135', 'Tội cố ý gây thương tích hoặc gây tổn hại cho sức khỏe của người khác trong trạng thái tinh thần bị kích động mạnh'),
('136', 'Tội cố ý gây thương tích hoặc gây tổn hại cho sức khoẻ của người khác do vượt quá giới hạn phòng vệ chính đáng hoặc do vượt quá mức cần thiết khi bắt giữ người phạm tội'),
('137', 'Tội gây thương tích hoặc gây tổn hại cho sức khoẻ của người khác trong khi thi hành công vụ'),
('138', 'Tội vô ý gây thương tích hoặc gây tổn hại cho sức khỏe của người khác'),
('139', 'Tội vô ý gây thương tích hoặc gây tổn hại cho sức khoẻ của người khác do vi phạm quy tắc nghề nghiệp hoặc quy tắc hành chính'),
('140', 'Tội hành hạ người khác'),
('141', 'Tội hiếp dâm'),
('142', 'Tội hiếp dâm người dưới 16 tuổi'),
('143', 'Tội cưỡng dâm'),
('144', 'Tội cưỡng dâm người từ đủ 13 tuổi đến dưới 16 tuổi'),
('145', 'Tội giao cấu hoặc thực hiện hành vi quan hệ tình dục khác với người từ đủ 13 tuổi đến dưới 16 tuổi'),
('146', 'Tội dâm ô đối với người dưới 16 tuổi'),
('147', 'Tội sử dụng người dưới 16 tuổi vào mục đích khiêu dâm'),
('148', 'Tội lây truyền HIV cho người khác'),
('149', 'Tội cố ý truyền HIV cho người khác'),
('150', 'Tội mua bán người'),
('151', 'Tội mua bán người dưới 16 tuổi'),
('152', 'Tội đánh tráo người dưới 01 tuổi'),
('153', 'Tội chiếm đoạt người dưới 16 tuổi'),
('154', 'Tội mua bán, chiếm đoạt mô hoặc bộ phận cơ thể người'),
('155', 'Tội làm nhục người khác'),
('156', 'Tội vu khống'),
('157', 'Tội bắt, giữ hoặc giam người trái pháp luật'),
('158', 'Tội xâm phạm chỗ ở của người khác'),
('159', 'Tội xâm phạm bí mật hoặc an toàn thư tín, điện thoại, điện tín hoặc hình thức trao đổi thông tin riêng tư khác của người khác'),
('160', 'Tội xâm phạm quyền của công dân về bầu cử, ứng cử hoặc biểu quyết khi Nhà nước trưng cầu ý dân'),
('161', 'Tội làm sai lệch kết quả bầu cử, kết quả trưng cầu ý dân'),
('162', 'Tội buộc công chức, viên chức thôi việc hoặc sa thải người lao động trái pháp luật'),
('163', 'Tội xâm phạm quyền hội họp, lập hội của công dân'),
('164', 'Tội xâm phạm quyền tự do tín ngưỡng, tôn giáo của người khác'),
('165', 'Tội xâm phạm quyền bình đẳng giới'),
('166', 'Tội xâm phạm quyền khiếu nại, tố cáo'),
('167', 'Tội xâm phạm quyền tự do ngôn luận, tự do báo chí, tiếp cận thông tin, quyền biểu tình của công dân'),
('168', 'Tội cướp tài sản'),
('169', 'Tội bắt cóc nhằm chiếm đoạt tài sản'),
('170', 'Tội cưỡng đoạt tài sản'),
('171', 'Tội cướp giật tài sản'),
('172', 'Tội công nhiên chiếm đoạt tài sản'),
('173', 'Tội trộm cắp tài sản'),
('174', 'Tội lừa đảo chiếm đoạt tài sản'),
('175', 'Tội lạm dụng tín nhiệm chiếm đoạt tài sản'),
('176', 'Tội chiếm giữ trái phép tài sản'),
('177', 'Tội sử dụng trái phép tài sản'),
('178', 'Tội hủy hoại hoặc cố ý làm hư hỏng tài sản'),
('179', 'Tội thiếu trách nhiệm gây thiệt hại đến tài sản của Nhà nước, cơ quan, tổ chức, doanh nghiệp'),
('180', 'Tội vô ý gây thiệt hại nghiêm trọng đến tài sản'),
('181', 'Tội cưỡng ép kết hôn, ly hôn hoặc cản trở hôn nhân tự nguyện, tiến bộ, cản trở ly hôn tự nguyện'),
('182', 'Tội vi phạm chế độ một vợ, một chồng'),
('183', 'Tội tổ chức tảo hôn'),
('184', 'Tội loạn luân'),
('185', 'Tội ngược đãi hoặc hành hạ ông bà, cha mẹ, vợ chồng, con, cháu hoặc người có công nuôi dưỡng mình'),
('186', 'Tội từ chối hoặc trốn tránh nghĩa vụ cấp dưỡng'),
('187', 'Tội tổ chức mang thai hộ vì mục đích thương mại'),
('188', 'Tội buôn lậu'),
('189', 'Tội vận chuyển trái phép hàng hóa, tiền tệ qua biên giới'),
('190', 'Tội sản xuất, buôn bán hàng cấm'),
('191', 'Tội tàng trữ, vận chuyển hàng cấm'),
('192', 'Tội sản xuất, buôn bán hàng giả'),
('193', 'Tội sản xuất, buôn bán hàng giả là lương thực, thực phẩm, phụ gia thực phẩm'),
('194', 'Tội sản xuất, buôn bán hàng giả là thuốc chữa bệnh, thuốc phòng bệnh'),
('195', 'Tội sản xuất, buôn bán hàng giả là thức ăn dùng để chăn nuôi, phân bón, thuốc thú y, thuốc bảo vệ thực vật, giống cây trồng, vật nuôi'),
('196', 'Tội đầu cơ'),
('197', 'Tội quảng cáo gian dối'),
('198', 'Tội lừa dối khách hàng'),
('199', 'Tội vi phạm các quy định về cung ứng điện'),
('200', 'Tội trốn thuế'),
('201', 'Tội cho vay lãi nặng trong giao dịch dân sự'),
('202', 'Tội làm, buôn bán tem giả, vé giả'),
('203', 'Tội in, phát hành, mua bán trái phép hóa đơn, chứng từ thu nộp ngân sách nhà nước'),
('204', 'Tội vi phạm quy định về bảo quản, quản lý hóa đơn, chứng từ thu nộp ngân sách nhà nước'),
('205', 'Tội lập quỹ trái phép'),
('206', 'Tội vi phạm quy định trong hoạt động của các tổ chức tín dụng, chi nhánh ngân hàng nước ngoài'),
('207', 'Tội làm, tàng trữ, vận chuyển, lưu hành tiền giả'),
('209', 'Tội cố ý công bố thông tin sai lệch hoặc che giấu thông tin trong hoạt động chứng khoán'),
('210', 'Tội sử dụng thông tin nội bộ để mua bán chứng khoán'),
('211', 'Tội thao túng thị trường chứng khoán'),
('212', 'Tội làm giả tài liệu trong hồ sơ chào bán, niêm yết chứng khoán'),
('213', 'Tội gian lận trong kinh doanh bảo hiểm'),
('214', 'Tội gian lận bảo hiểm xã hội, bảo hiểm thất nghiệp'),
('215', 'Tội gian lận bảo hiểm y tế'),
('216', 'Tội trốn đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp cho người lao động'),
('217', 'Tội vi phạm quy định về cạnh tranh'),
('218', 'Tội vi phạm quy định về hoạt động bán đấu giá tài sản'),
('219', 'Tội vi phạm quy định về quản lý, sử dụng tài sản Nhà nước gây thất thoát, lãng phí'),
('220', 'Tội vi phạm qui định của Nhà nước về quản lý và sử dụng vốn đầu tư công gây hậu quả nghiêm trọng'),
('221', 'Tội vi phạm quy định của Nhà nước về kế toán gây hậu quả nghiêm trọng'),
('222', 'Tội vi phạm quy định về đấu thầu gây hậu quả nghiêm trọng'),
('223', 'Tội thông đồng, bao che cho người nộp thuế gây hậu quả nghiêm trọng'),
('224', 'Tội vi phạm quy định về đầu tư công trình xây dựng gây hậu quả nghiêm trọng'),
('225', 'Tội xâm phạm quyền tác giả, quyền liên quan'),
('226', 'Tội xâm phạm quyền sở hữu công nghiệp'),
('227', 'Tội vi phạm các quy định về nghiên cứu, thăm dò, khai thác tài nguyên'),
('228', 'Tội vi phạm các quy định về sử dụng đất đai'),
('229', 'Tội vi phạm các quy định về quản lý đất đai'),
('230', 'Tội vi phạm quy định về bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất'),
('231', 'Tội cố ý làm trái quy định về phân phối tiền, hàng cứu trợ'),
('232', 'Tội vi phạm các quy định về khai thác, bảo vệ rừng và quản lý lâm sản'),
('233', 'Tội vi phạm các quy định về quản lý rừng'),
('234', 'Tội vi phạm quy định về quản lý, bảo vệ động vật hoang dã'),
('235', 'Tội gây ô nhiễm môi trường'),
('236', 'Tội vi phạm quy định về quản lý chất thải nguy hại'),
('237', 'Tội vi phạm quy định về phòng ngừa, ứng phó, khắc phục sự cố môi trường'),
('238', 'Tội vi phạm quy định về bảo vệ an toàn công trình thủy lợi, đê điều và phòng, chống thiên tai; vi phạm quy định về bảo vệ bờ, bãi sông'),
('239', 'Tội đưa chất thải vào lãnh thổ Việt Nam'),
('240', 'Tội làm lây lan dịch bệnh truyền nhiễm nguy hiểm cho người'),
('241', 'Tội làm lây lan dịch bệnh nguy hiểm cho động vật, thực vật'),
('242', 'Tội huỷ hoại nguồn lợi thuỷ sản'),
('243', 'Tội huỷ hoại rừng'),
('244', 'Tội vi phạm quy định về quản lý, bảo vệ động vật nguy cấp, quý, hiếm'),
('245', 'Tội vi phạm các quy định về quản lý khu bảo tồn thiên nhiên'),
('246', 'Tội nhập khẩu, phát tán các loài ngoại lai xâm hại'),
('247', 'Tội trồng cây thuốc phiện, cây côca, cây cần sa hoặc các loại cây khác có chứa chất ma túy'),
('248', 'Tội sản xuất trái phép chất ma túy'),
('249', 'Tội tàng trữ trái phép chất ma túy'),
('250', 'Tội vận chuyển trái phép chất ma túy'),
('251', 'Tội mua bán trái phép chất ma túy'),
('252', 'Tội chiếm đoạt chất ma túy'),
('253', 'Tội tàng trữ, vận chuyển, mua bán hoặc chiếm đoạt tiền chất dùng vào việc sản xuất trái phép chất ma túy'),
('254', 'Tội sản xuất, tàng trữ, vận chuyển hoặc mua bán phương tiện, dụng cụ dùng vào việc sản xuất hoặc sử dụng trái phép chất ma túy'),
('255', 'Tội tổ chức sử dụng trái phép chất ma túy'),
('256', 'Tội chứa chấp việc sử dụng trái phép chất ma túy'),
('257', 'Tội cưỡng bức người khác sử dụng trái phép chất ma túy'),
('258', 'Tội lôi kéo người khác sử dụng trái phép chất ma túy'),
('259', 'Tội vi phạm quy định về quản lý, sử dụng chất ma túy, tiền chất, thuốc gây nghiện, thuốc hướng thần'),
('260', 'Tội vi phạm quy định về tham gia giao thông đường bộ'),
('261', 'Tội cản trở giao thông đường bộ'),
('262', 'Tội đưa vào sử dụng các phương tiện giao thông cơ giới đường bộ, xe máy chuyên dùng không bảo đảm tiêu chuẩn an toàn kỹ thuật tham gia giao thông'),
('263', 'Tội điều động người không đủ điều kiện điều khiển các phương tiện tham gia giao thông đường bộ'),
('264', 'Tội giao cho người không đủ điều kiện điều khiển các phương tiện tham gia giao thông đường bộ'),
('265', 'Tội tổ chức đua xe trái phép'),
('266', 'Tội đua xe trái phép'),
('267', 'Tội vi phạm quy định về điều khiển phương tiện giao thông đường sắt'),
('268', 'Tội cản trở giao thông đường sắt'),
('269', 'Tội đưa vào sử dụng các phương tiện, thiết bị giao thông đường sắt không bảo đảm an toàn'),
('270', 'Tội điều động người không đủ điều kiện điều khiển các phương tiện giao thông đường sắt'),
('271', 'Tội giao cho người không đủ điều kiện điều khiển các phương tiện giao thông đường sắt'),
('272', 'Tội vi phạm quy định về điều khiển phương tiện giao thông đường thuỷ'),
('273', 'Tội cản trở giao thông đường thuỷ'),
('274', 'Tội đưa vào sử dụng các phương tiện giao thông đường thuỷ không bảo đảm an toàn'),
('275', 'Tội điều động người không đủ điều kiện điều khiển các phương tiện giao thông đường thuỷ'),
('276', 'Tội giao cho người không đủ điều kiện điều khiển các phương tiện giao thông đường thuỷ'),
('277', 'Tội vi phạm quy định điều khiển tàu bay'),
('278', 'Tội cản trở giao thông đường không'),
('279', 'Tội đưa vào sử dụng phương tiện giao thông đường không không bảo đảm an toàn'),
('280', 'Tội điều động hoặc giao cho người không đủ điều kiện điều khiển các phương tiện giao thông đường không'),
('281', 'Tội vi phạm quy định về duy tu, sửa chữa, quản lý các công trình giao thông'),
('282', 'Tội chiếm đoạt tàu bay, tàu thuỷ'),
('283', 'Tội điều khiển tàu bay vi phạm các quy định về hàng không của nước Cộng hòa xã hội chủ nghĩa Việt Nam'),
('284', 'Tội điều khiển phương tiện hàng hải vi phạm các quy định về hàng hải của nước Cộng hòa xã hội chủ nghĩa Việt Nam'),
('285', 'Tội sản xuất, mua bán, trao đổi hoặc tặng cho công cụ, thiết bị, phần mềm để sử dụng vào mục đích trái pháp luật'),
('286', 'Tội phát tán chương trình tin học gây hại cho hoạt động của mạng máy tính, mạng viễn thông, phương tiện điện tử'),
('287', 'Tội cản trở hoặc gây rối loạn hoạt động của mạng máy tính, mạng viễn thông, phương tiện điện tử'),
('288', 'Tội đưa hoặc sử dụng trái phép thông tin mạng máy tính, mạng viễn thông'),
('289', 'Tội xâm nhập trái phép vào mạng máy tính, mạng viễn thông hoặc phương tiện điện tử của người khác'),
('290', 'Tội sử dụng mạng máy tính, mạng viễn thông, phương tiện điện tử thực hiện hành vi chiếm đoạt tài sản'),
('291', 'Tội thu thập, tàng trữ, trao đổi, mua bán, công khai hóa trái phép thông tin về tài khoản ngân hàng'),
('292', 'Tội cung cấp dịch vụ trái phép trên mạng máy tính, mạng viễn thông'),
('293', 'Tội sử dụng trái phép tần số vô tuyến điện dành riêng cho mục đích cấp cứu, an toàn, tìm kiếm, cứu hộ, cứu nạn, quốc phòng, an ninh'),
('294', 'Tội cố ý gây nhiễu có hại'),
('295', 'Tội vi phạm quy định về an toàn lao động, vệ sinh lao động, về an toàn ở những nơi đông người'),
('296', 'Tội vi phạm quy định về sử dụng người lao động dưới 16 tuổi'),
('297', 'Tội cưỡng bức lao động'),
('298', 'Tội vi phạm quy định về xây dựng gây hậu quả nghiêm trọng'),
('299', 'Tội khủng bố'),
('300', 'Tội tài trợ khủng bố'),
('301', 'Tội bắt cóc con tin'),
('302', 'Tội cướp biển'),
('303', 'Tội phá huỷ công trình, cơ sở, phương tiện quan trọng về an ninh quốc gia'),
('304', 'Tội chế tạo, tàng trữ, vận chuyển, sử dụng, mua bán trái phép hoặc chiếm đoạt vũ khí quân dụng, phương tiện kỹ thuật quân sự'),
('305', 'Tội chế tạo, tàng trữ, vận chuyển, sử dụng, mua bán trái phép hoặc chiếm đoạt vật liệu nổ'),
('306', 'Tội chế tạo, tàng trữ, vận chuyển, sử dụng, mua bán trái phép hoặc chiếm đoạt súng săn, vũ khí thô sơ, vũ khí thể thao, công cụ hỗ trợ và các vũ khí khác có tính năng tác dụng tương tự'),
('307', 'Tội vi phạm quy định về quản lý vũ khí, vật liệu nổ, công cụ hỗ trợ'),
('308', 'Tội thiếu trách nhiệm trong việc giữ vũ khí, vật liệu nổ, công cụ hỗ trợ gây hậu quả nghiêm trọng'),
('309', 'Tội sản xuất, tàng trữ, vận chuyển, sử dụng, phát tán, mua bán trái phép hoặc chiếm đoạt chất phóng xạ, vật liệu hạt nhân'),
('310', 'Tội vi phạm quy định về quản lý chất phóng xạ, vật liệu hạt nhân'),
('311', 'Tội sản xuất, tàng trữ, vận chuyển, sử dụng hoặc mua bán trái phép chất cháy, chất độc'),
('312', 'Tội vi phạm quy định về quản lý chất cháy, chất độc'),
('313', 'Tội vi phạm quy định về phòng cháy, chữa cháy'),
('314', 'Tội vi phạm quy định về an toàn vận hành công trình điện'),
('315', 'Tội vi phạm quy định về khám bệnh, chữa bệnh, sản xuất, pha chế thuốc, cấp phát thuốc, bán thuốc hoặc dịch vụ y tế khác'),
('316', 'Tội phá thai trái phép'),
('317', 'Tội vi phạm quy định về vệ sinh an toàn thực phẩm'),
('318', 'Tội gây rối trật tự công cộng'),
('319', 'Tội xâm phạm thi thể, mồ mả, hài cốt'),
('320', 'Tội hành nghề mê tín, dị đoan'),
('321', 'Tội đánh bạc'),
('322', 'Tội tổ chức đánh bạc hoặc gá bạc'),
('323', 'Tội chứa chấp hoặc tiêu thụ tài sản do người khác phạm tội mà có'),
('324', 'Tội rửa tiền'),
('325', 'Tội dụ dỗ, ép buộc hoặc chứa chấp người dưới 18 tuổi phạm pháp'),
('326', 'Tội truyền bá văn hóa phẩm đồi trụy'),
('327', 'Tội chứa mại dâm'),
('328', 'Tội môi giới mại dâm'),
('329', 'Tội mua dâm người dưới 18 tuổi'),
('330', 'Tội chống người thi hành công vụ'),
('331', 'Tội lợi dụng các quyền tự do dân chủ xâm phạm lợi ích của Nhà nước, quyền, lợi ích hợp pháp của tổ chức, cá nhân'),
('332', 'Tội trốn tránh nghĩa vụ quân sự'),
('333', 'Tội không chấp hành lệnh gọi quân nhân dự bị nhập ngũ'),
('334', 'Tội làm trái quy định về việc thực hiện nghĩa vụ quân sự'),
('335', 'Tội cản trở việc thực hiện nghĩa vụ quân sự'),
('336', 'Tội đăng ký hộ tịch trái pháp luật'),
('337', 'Tội cố ý làm lộ bí mật nhà nước'),
('338', 'Tội vô ý làm lộ bí mật nhà nước'),
('339', 'Tội giả mạo chức vụ, cấp bậc, vị trí công tác'),
('340', 'Tội sửa chữa và sử dụng giấy chứng nhận, các tài liệu của cơ quan, tổ chức'),
('341', 'Tội làm giả con dấu, tài liệu của cơ quan, tổ chức'),
('342', 'Tội chiếm đoạt, mua bán, tiêu hủy con dấu, tài liệu của cơ quan, tổ chức'),
('343', 'Tội vi phạm các quy định về quản lý nhà ở'),
('344', 'Tội vi phạm các quy định về hoạt động xuất bản'),
('345', 'Tội vi phạm các quy định về bảo vệ và sử dụng di tích lịch sử - văn hóa, danh lam, thắng cảnh gây hậu quả nghiêm trọng'),
('346', 'Tội vi phạm quy chế về khu vực biên giới'),
('347', 'Tội vi phạm quy định về xuất cảnh, nhập cảnh'),
('348', 'Tội tổ chức, môi giới cho người khác xuất cảnh, nhập cảnh hoặc ở lại Việt Nam trái phép'),
('349', 'Tội tổ chức, môi giới cho người khác trốn đi nước ngoài hoặc ở lại nước ngoài trái phép'),
('350', 'Tội cưỡng ép người khác trốn đi nước ngoài hoặc ở lại nước ngoài trái phép'),
('351', 'Tội xúc phạm Quốc kỳ, Quốc huy, Quốc ca'),
('353', 'Tội tham ô tài sản'),
('354', 'Tội nhận hối lộ'),
('355', 'Tội lạm dụng chức vụ, quyền hạn chiếm đoạt tài sản'),
('356', 'Tội lợi dụng chức vụ, quyền hạn trong khi thi hành công vụ'),
('357', 'Tội lạm quyền trong khi thi hành công vụ'),
('358', 'Tội lợi dụng chức vụ, quyền hạn gây ảnh hưởng đối với người khác để trục lợi'),
('359', 'Tội giả mạo trong công tác'),
('360', 'Tội thiếu trách nhiệm gây hậu quả nghiêm trọng'),
('361', 'Tội cố ý làm lộ bí mật công tác'),
('362', 'Tội vô ý làm lộ bí mật công tác'),
('363', 'Tội đào nhiệm'),
('364', 'Tội đưa hối lộ'),
('365', 'Tội môi giới hối lộ'),
('366', 'Tội lợi dụng ảnh hưởng đối với người có chức vụ quyền hạn để trục lợi'),
('368', 'Tội truy cứu trách nhiệm hình sự người không có tội'),
('369', 'Tội không truy cứu trách nhiệm hình sự người có tội'),
('370', 'Tội ra bản án trái pháp luật'),
('371', 'Tội ra quyết định trái pháp luật'),
('372', 'Tội ép buộc người có thẩm quyền trong hoạt động tư pháp làm trái pháp luật'),
('373', 'Tội dùng nhục hình'),
('374', 'Tội bức cung'),
('375', 'Tội làm sai lệch hồ sơ vụ án, vụ việc'),
('376', 'Tội thiếu trách nhiệm để người bị bắt, người bị tạm giữ, tạm giam, người đang chấp hành án phạt tù trốn'),
('377', 'Tội lợi dụng chức vụ, quyền hạn giam, giữ người trái pháp luật'),
('378', 'Tội tha trái pháp luật người bị bắt, người đang bị tạm giữ, tạm giam, người đang chấp hành án phạt tù'),
('379', 'Tội không thi hành án'),
('380', 'Tội không chấp hành án'),
('381', 'Tội cản trở việc thi hành án'),
('382', 'Tội cung cấp tài liệu sai sự thật hoặc khai báo gian dối'),
('383', 'Tội từ chối khai báo, từ chối kết luận giám định, định giá tài sản hoặc từ chối cung cấp tài liệu'),
('384', 'Tội mua chuộc hoặc cưỡng ép người khác trong việc khai báo, cung cấp tài liệu'),
('385', 'Tội vi phạm việc niêm phong, kê biên tài sản, phong tỏa tài khoản'),
('386', 'Tội trốn khỏi nơi giam, giữ hoặc trốn khi đang bị áp giải, đang bị xét xử'),
('387', 'Tội đánh tháo người bị bắt, bị tạm giữ, tạm giam, người đang bị áp giải, xét xử, chấp hành án phạt tù'),
('388', 'Tội vi phạm quy định về giam giữ'),
('389', 'Tội che giấu tội phạm'),
('390', 'Tội không tố giác tội phạm'),
('391', 'Tội gây rối trật tự phiên tòa'),
('393', 'Tội ra mệnh lệnh trái pháp luật'),
('394', 'Tội chống mệnh lệnh'),
('395', 'Tội chấp hành không nghiêm chỉnh mệnh lệnh'),
('396', 'Tội cản trở đồng đội thực hiện nhiệm vụ'),
('397', 'Tội làm nhục đồng đội'),
('398', 'Tội hành hung đồng đội'),
('399', 'Tội đầu hàng địch'),
('400', 'Tội khai báo hoặc tự nguyện làm việc cho địch khi bị bắt làm tù binh'),
('401', 'Tội bỏ vị trí chiến đấu hoặc không làm nhiệm vụ trong chiến đấu'),
('402', 'Tội đào ngũ'),
('403', 'Tội trốn tránh nhiệm vụ'),
('404', 'Tội cố ý làm lộ bí mật công tác quân sự'),
('405', 'Tội chiếm đoạt, mua bán hoặc tiêu huỷ tài liệu bí mật công tác quân sự'),
('406', 'Tội vô ý làm lộ bí mật công tác quân sự'),
('407', 'Tội làm mất tài liệu bí mật công tác quân sự'),
('408', 'Tội báo cáo sai'),
('409', 'Tội vi phạm quy định về trực ban, trực chiến, trực chỉ huy'),
('410', 'Tội vi phạm quy định về bảo vệ'),
('411', 'Tội vi phạm các quy định về bảo đảm an toàn trong chiến đấu hoặc trong huấn luyện'),
('412', 'Tội vi phạm quy định về sử dụng vũ khí quân dụng, trang bị kỹ thuật quân sự'),
('413', 'Tội huỷ hoại hoặc cố ý làm hư hỏng vũ khí quân dụng, trang bị kỹ thuật quân sự'),
('414', 'Tội làm mất hoặc vô ý làm hư hỏng vũ khí quân dụng, phương tiện kỹ thuật quân sự'),
('415', 'Tội quấy nhiễu nhân dân'),
('416', 'Tội lạm dụng nhu cầu quân sự trong khi thực hiện nhiệm vụ'),
('417', 'Tội cố ý bỏ thương binh, tử sỹ hoặc không chăm sóc, cứu chữa thương binh'),
('418', 'Tội chiếm đoạt hoặc huỷ hoại di vật của tử sỹ'),
('419', 'Tội chiếm đoạt hoặc huỷ hoại chiến lợi phẩm'),
('420', 'Tội ngược đãi tù binh, hàng binh'),
('421', 'Tội phá hoại hòa bình, gây chiến tranh xâm lược'),
('422', 'Tội chống loài người'),
('423', 'Tội phạm chiến tranh'),
('424', 'Tội tuyển mộ, huấn luyện hoặc sử dụng lính đánh thuê'),
('425', 'Tội làm lính đánh thuê');